[project]
name = "jira-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "jira>=3.8.0",
    "mcp[cli]>=1.8.1",
]
